#YAML
#
# Raw data
#
volatility_calculation:
  func: "syscore.algos.robust_vol_calc"
  days: 35
#
# Trading rules
#
trading_rules:
  ewmac2_8:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args: 
         Lfast: 2
         Lslow: 8
     forecast_scalar: 10.6
  ewmac4_16:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args: 
         Lfast: 4
         Lslow: 16
     forecast_scalar: 7.5
  ewmac8_32:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args: 
         Lfast: 8
         Lslow: 32
     forecast_scalar: 5.3
  ewmac16_64:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args: 
         Lfast: 16
         Lslow: 64
     forecast_scalar: 3.75
  ewmac32_128:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args: 
         Lfast: 32
         Lslow: 128
     forecast_scalar: 2.65
  ewmac64_256:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args: 
         Lfast: 64
         Lslow: 256
     forecast_scalar: 1.87
#   carry:
#      function: systems.provided.futures_chapter15.rules.carry
#      data:
#          - "rawdata.daily_annualised_roll"
#          - "rawdata.daily_returns_volatility"                      Uncomment this i "quit" Carry from the trading rules
#      other_args:
#          smooth_days: 90
#      forecast_scalar: 30
forecast_cap: 20.0
#
# forecast combination
#
use_forecast_weight_estimates: True
#use_forecast_div_mult_estimates: True     This line cause system crash.

#
# Capital correction
#
percentage_vol_target: 20.0
notional_trading_capital: 250000
base_currency: "USD"
#
# Portfolio creation
#
use_instrument_weight_estimates : True
#use_instrument_div_mult_estimates: True     This line cause system crash.

rule_groups:
    ewmac_fast:
       - ewmac2_8
       - ewmac4_16
    ewmac_medium:
       - ewmac8_32
       - ewmac16_64
    ewmac_slow:
       - ewmac32_128
       - ewmac64_256
    carry:
       - carry
style_groups:
    trend:
        - ewmac_fast
        - ewmac_medium
        - ewmac_slow
    carry:
        - carry
countries:
    US:
      - EDOLLAR
      - US10
    Europe:
      - EUROSTX
      - V2X
    Other:
    - MXP
    - CORN
asset_classes:
    Rates:
      - EDOLLAR
      - US10
    Risky:
      - EUROSTX
      - V2X
      - MXP
    Other:
      - CORN

